apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
spec:
  template:
    spec:
      containers:
      - name: migration
        image: mokarski/user-service-migration:v1
        envFrom:
        - secretRef:
            name: db-secret
      restartPolicy: Never
  backoffLimit: 2
