apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: YWRtaW4=  # admin
  DB_PASSWORD: YWRtaW4xMjM=  # admin123
  DB_NAME: dXNlcmRi  # userdb
  DB_HOST: cG9zdGdyZXNxbC1wcmltYXJ5  # postgresql-primary
